### PR TITLE
add dict default arg to dag constructor

### PR DESCRIPTION
**Pull request by dwcoates**
Small convenience change for creating DAGs

### CODE REVIEW

**Comment by thieman** [comment]
Hello! I'm fine with this addition conceptually, you just need to clean it up a bit.

In terms of the actual implementation, you've introduced a slight inefficiency by leaving the original `reset_graph` call in place, since you are now double-initializing the graph object in both cases. I think a cleaner implementation would be to call `reset_graph` as we are now if the optional arg is `None`, and if not then to call `from_dict` with your initializer. 

This also needs to be tested before we can merge it. Please add a test confirming that the DAG behaves as expected if you provide a graph to the initializer.

We're working on integrating Python 3 support and will cut a new release in the next few days. If you can get this finished up before then we can get it in with that.

**Comment by thieman** [comment]
Additionally, please change the constructor's docstring to reflect how it works with your changes.

**Comment by dwcoates** [comment]
Ah, I intended to delete the first call, but forgot. This amounts to just routing initialization through from_dict and letting it handling the resetting, with default construction essentially being a from_dict call on an empty dict. 

I'll try to get the rest done soon, thanks.

**Comment by thieman** [comment]
Cool. This was probably unintentional, but please do not include the predecessors stuff in the same PR as the constructor change.

**Comment by dwcoates** [comment]
Yeah, should have branched :O

**Comment by thieman** [comment]
Still looking for a change to the docstring and some tests before we can merge this

**Comment by thieman** [comment]
Closing due to inactivity

**Pull request closed without merging**
