### PR TITLE
all_leaves() functionality.

### PR DESCRIPTION
**Pull request by rclough**
Small and straightforward, an O(n) implementation that returns all nodes without a downstream (aka, a "leaf"

### CODE REVIEW

**Comment by thieman** [comment]
LGTM, need to rebase

**Comment by rclough** [comment]
this is a great time to learn to rebase! lemme do that now

**Comment by rclough** [comment]
I *think* I rebased it

**Comment by rclough** [comment]
yeah code looks right. just always weary of doing a push -f

**Pull request merged**
