### PR TITLE
Python 2 and 3 compatibility

### PR DESCRIPTION
**Pull request by chakmidlot**
I want to port your Dagobah and py-dag to Python 3.

### CODE REVIEW

**Comment by thieman** [comment]
Hey I'm sorry, I totally didn't even see this before today. I'll try to take a look this weekend.

**Comment by chakmidlot** [comment]
If you merge this commit I will prepare Dagobah PR for compatibility with pyhton2 and python3. And thank you for your project.

**Comment by thieman** [comment]
1. I'd like to preserve the generator qualities of item iteration in Python 2. Can you try using `future.utils.iteritems` as suggested here? http://python-future.org/compatible_idioms.html
1. Please remove the version bump from this PR, we'll do that separately. I will also want to get the Travis build passing in Python 3 before we bump the version and release.
1. You'll need to rebase and potentially fix any compatibility issues in the new public method I added recently.

**Comment by thieman** [comment]
Actually you might be able to use this without having to add a dependency, which would be better. https://docs.python.org/2/library/stdtypes.html#dict.viewitems

**Comment by chakmidlot** [comment]
Done

**Comment by thieman** [comment]
Please go ahead and do a quick rebase on master so we're only looking at your changes :smile:

**Pull request closed without merging**
