### PR TITLE
Move from deep to shallow copy for temporary copies of graph

### PR DESCRIPTION
**Pull request by MrPowers**
…x types

### CODE REVIEW

**Comment by MrPowers** [comment]
@thieman - Thanks for creating this library.  It's helping me a ton!

If we change the deep copy to a shallow copy, then the vertices (aka nodes) can be arbitrary objects.  The deep copy approach works when the nodes are strings or integers, but doesn't work when the nodes are user created objects.

This pull request makes is so code like this will work:

```python
class Person:
  def __init__(self, first_name):
    self.first_name = first_name
p1 = Person("paula")
p2 = Person("drew")
dag.add_node(p1)
dag.add_node(p2)
dag.add_edge(p1, p2)
```

Let me know what you think!

**Comment by thieman** [comment]
Thanks for the PR! I'm struggling to think of any reason why this _wouldn't_ be okay, or why this was a `deepcopy` in the first place. It...seems fine to me? I'll try to take it for a spin this weekend and see if I can break it. I definitely agree it'd be nice to handle more user-defined objects if possible.

**Comment by thieman** [comment]
Alright, turns out this does not work. The line right after the deepcopy is modifying the adjacent sets in the graph. With the shallow copy, they get permanently modified. This works fine as long as you are always adding valid edges. If you add an invalid edge, you have now corrupted your graph. Here's a test:

```
@with_setup(blank_setup)
def test_validate_failure_does_not_permanently_corrupt():
    dag.add_node('a')
    dag.add_node('b')
    dag.add_edge('a', 'b')

    try:
        dag.add_edge('b', 'a')    
    except DAGValidationError:
        pass

    # We caught the error, but our graph was permanently modified
    # This is why we were using deepcopy previously
    assert dag.validate() is True
```

Seems like we could still handle this in this case by undoing our change to the set in the event that we can't validate. Want to add this test case in and give it another go?

**Comment by MrPowers** [comment]
Thanks for responding!  Think I'm going to look for another library cause I need something with the [shortest path algo](https://github.com/thieman/py-dag/issues/29) and this fix.  Thanks again for making this lib!

**Pull request closed without merging**
